//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string ParentItem { get; set; }
        public string ChildItem { get; set; }
        public decimal Qty { get; set; }
        public string Remarks { get; set; }
        public decimal Scrape { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Operator { get; set; }
        public string ModifyName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual 物料资料 物料资料 { get; set; }
    }
}
