//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qds236354159_dbEntities : DbContext
    {
        public qds236354159_dbEntities()
            : base("name=qds236354159_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<采购单> 采购单 { get; set; }
        public virtual DbSet<采购单明细> 采购单明细 { get; set; }
        public virtual DbSet<采购入库> 采购入库 { get; set; }
        public virtual DbSet<采购物料资料> 采购物料资料 { get; set; }
        public virtual DbSet<仓位> 仓位 { get; set; }
        public virtual DbSet<供应商资料> 供应商资料 { get; set; }
        public virtual DbSet<库存明细> 库存明细 { get; set; }
        public virtual DbSet<退货单> 退货单 { get; set; }
        public virtual DbSet<退货单明细> 退货单明细 { get; set; }
        public virtual DbSet<退货入库> 退货入库 { get; set; }
        public virtual DbSet<物料类型> 物料类型 { get; set; }
        public virtual DbSet<物料资料> 物料资料 { get; set; }
        public virtual DbSet<用户> 用户 { get; set; }
        public virtual DbSet<组> 组 { get; set; }
    }
}
