//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreSaleDetail
    {
        public int RelationNumber { get; set; }
        public string MaterialID { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Residue { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public bool Statement { get; set; }
        public string Remark { get; set; }
        public decimal CompletedQuantity { get; set; }
        public int PlanID { get; set; }
        public string ModifyName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual PreSale PreSale { get; set; }
    }
}
