//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 仓位
    {
        public 仓位()
        {
            this.采购入库 = new HashSet<采购入库>();
            this.退货入库 = new HashSet<退货入库>();
        }
    
        public string Store { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ItemPlan { get; set; }
    
        public virtual ICollection<采购入库> 采购入库 { get; set; }
        public virtual ICollection<退货入库> 退货入库 { get; set; }
    }
}
