//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 供应商资料
    {
        public 供应商资料()
        {
            this.采购单 = new HashSet<采购单>();
            this.采购单明细 = new HashSet<采购单明细>();
            this.采购物料资料 = new HashSet<采购物料资料>();
            this.退货单 = new HashSet<退货单>();
        }
    
        public string 供应商代码 { get; set; }
        public string 供应商名称 { get; set; }
        public string 主供项目 { get; set; }
        public string 地址 { get; set; }
        public string 联系人 { get; set; }
        public string 手机 { get; set; }
        public string 电话 { get; set; }
        public string 传真 { get; set; }
        public string EMail { get; set; }
        public string 备注 { get; set; }
        public string 结款方式 { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<采购单> 采购单 { get; set; }
        public virtual ICollection<采购单明细> 采购单明细 { get; set; }
        public virtual ICollection<采购物料资料> 采购物料资料 { get; set; }
        public virtual ICollection<退货单> 退货单 { get; set; }
    }
}
