//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 备货单明细
    {
        public int 备货单号 { get; set; }
        public int 关联单号 { get; set; }
        public string 物料编号 { get; set; }
        public decimal 数量 { get; set; }
        public decimal 备品 { get; set; }
        public string 备注 { get; set; }
        public bool 结单 { get; set; }
        public decimal 完成数量 { get; set; }
        public string ModifyName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual 备货单 备货单 { get; set; }
    }
}
