//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 物料资料
    {
        public 物料资料()
        {
            this.Bill = new HashSet<Bill>();
            this.采购单明细 = new HashSet<采购单明细>();
            this.采购入库 = new HashSet<采购入库>();
            this.采购物料资料 = new HashSet<采购物料资料>();
            this.库存明细 = new HashSet<库存明细>();
            this.退货单明细 = new HashSet<退货单明细>();
            this.退货入库 = new HashSet<退货入库>();
        }
    
        public string 物料编号 { get; set; }
        public string 名称规格 { get; set; }
        public string 单位 { get; set; }
        public Nullable<decimal> 单价 { get; set; }
        public Nullable<float> 税率 { get; set; }
        public string 物料类型 { get; set; }
        public decimal 最小包装 { get; set; }
        public string 备注 { get; set; }
        public string 版本 { get; set; }
        public Nullable<decimal> 净重 { get; set; }
        public Nullable<decimal> 总重 { get; set; }
        public string 操作员 { get; set; }
        public Nullable<int> 周期 { get; set; }
        public string 穴数 { get; set; }
        public string 模号 { get; set; }
        public Nullable<bool> 冻结 { get; set; }
        public Nullable<System.DateTime> 日期 { get; set; }
        public bool 核准 { get; set; }
        public string ModifyName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<Bill> Bill { get; set; }
        public virtual ICollection<采购单明细> 采购单明细 { get; set; }
        public virtual ICollection<采购入库> 采购入库 { get; set; }
        public virtual ICollection<采购物料资料> 采购物料资料 { get; set; }
        public virtual ICollection<库存明细> 库存明细 { get; set; }
        public virtual ICollection<退货单明细> 退货单明细 { get; set; }
        public virtual ICollection<退货入库> 退货入库 { get; set; }
        public virtual 物料类型 物料类型1 { get; set; }
    }
}
