//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 物料类型
    {
        public 物料类型()
        {
            this.物料资料 = new HashSet<物料资料>();
        }
    
        public string 物料类型1 { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<物料资料> 物料资料 { get; set; }
    }
}
