//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 用户
    {
        public 用户()
        {
            this.采购单 = new HashSet<采购单>();
            this.采购入库 = new HashSet<采购入库>();
            this.采购物料资料 = new HashSet<采购物料资料>();
            this.退货单 = new HashSet<退货单>();
            this.退货入库 = new HashSet<退货入库>();
        }
    
        public string 用户名 { get; set; }
        public string 组 { get; set; }
        public string 密码 { get; set; }
        public Nullable<bool> 冻结 { get; set; }
    
        public virtual ICollection<采购单> 采购单 { get; set; }
        public virtual ICollection<采购入库> 采购入库 { get; set; }
        public virtual ICollection<采购物料资料> 采购物料资料 { get; set; }
        public virtual ICollection<退货单> 退货单 { get; set; }
        public virtual ICollection<退货入库> 退货入库 { get; set; }
        public virtual 组 组1 { get; set; }
    }
}
