//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 退货单明细
    {
        public 退货单明细()
        {
            this.退货入库 = new HashSet<退货入库>();
        }
    
        public int ID { get; set; }
        public int 关联单号 { get; set; }
        public string 物料编号 { get; set; }
        public decimal 单价 { get; set; }
        public decimal 数量 { get; set; }
        public bool 结单 { get; set; }
        public string 备注 { get; set; }
        public bool 对账 { get; set; }
        public Nullable<decimal> 备品 { get; set; }
        public Nullable<decimal> Replenishment { get; set; }
        public Nullable<decimal> CompleteQuantity { get; set; }
    
        public virtual 退货单 退货单 { get; set; }
        public virtual 物料资料 物料资料 { get; set; }
        public virtual ICollection<退货入库> 退货入库 { get; set; }
    }
}
