//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 退货单
    {
        public 退货单()
        {
            this.退货单明细 = new HashSet<退货单明细>();
        }
    
        public int 单号 { get; set; }
        public string 供应商代码 { get; set; }
        public System.DateTime 日期 { get; set; }
        public string 操作员 { get; set; }
        public string 备注 { get; set; }
        public bool 结单 { get; set; }
    
        public virtual 供应商资料 供应商资料 { get; set; }
        public virtual 用户 用户 { get; set; }
        public virtual ICollection<退货单明细> 退货单明细 { get; set; }
    }
}
