//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 采购单明细
    {
        public 采购单明细()
        {
            this.采购入库 = new HashSet<采购入库>();
        }
    
        public int 关联单号 { get; set; }
        public string 物料编号 { get; set; }
        public decimal 单价 { get; set; }
        public decimal 数量 { get; set; }
        public decimal 税率 { get; set; }
        public decimal 备品 { get; set; }
        public Nullable<System.DateTime> 交货日期 { get; set; }
        public bool 结单 { get; set; }
        public string 备注 { get; set; }
        public decimal 完成数量 { get; set; }
        public string 供应商代码 { get; set; }
        public string PreSaleID { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyName { get; set; }
    
        public virtual 采购单 采购单 { get; set; }
        public virtual ICollection<采购入库> 采购入库 { get; set; }
    }
}
