//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 采购入库
    {
        public int ID { get; set; }
        public int 关联单号 { get; set; }
        public string 物料编号 { get; set; }
        public decimal 送货数量 { get; set; }
        public Nullable<decimal> 数量 { get; set; }
        public Nullable<decimal> 备品 { get; set; }
        public System.DateTime 日期 { get; set; }
        public string 仓位 { get; set; }
        public string 操作员 { get; set; }
        public bool 对账 { get; set; }
        public string 备注 { get; set; }
        public string 检验状态 { get; set; }
        public Nullable<decimal> harmful { get; set; }
        public Nullable<System.DateTime> QCTime { get; set; }
        public string QC { get; set; }
        public string QCRemarks { get; set; }
        public string StoreStaff { get; set; }
        public Nullable<System.DateTime> InStoreTime { get; set; }
    
        public virtual 采购单明细 采购单明细 { get; set; }
    }
}
