//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 采购单
    {
        public 采购单()
        {
            this.采购单明细 = new HashSet<采购单明细>();
        }
    
        public int 单号 { get; set; }
        public string 供应商代码 { get; set; }
        public System.DateTime 日期 { get; set; }
        public string 操作员 { get; set; }
        public string 备注 { get; set; }
        public bool 结单 { get; set; }
        public string 结款方式 { get; set; }
        public string 供应商名称 { get; set; }
    
        public virtual ICollection<采购单明细> 采购单明细 { get; set; }
    }
}
