//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class 采购物料资料
    {
        public string 供应商代码 { get; set; }
        public string 物料编号 { get; set; }
        public string 供应商料号 { get; set; }
        public Nullable<decimal> 单价 { get; set; }
        public Nullable<decimal> 税率 { get; set; }
        public string 备注 { get; set; }
        public string Opetator { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual 供应商资料 供应商资料 { get; set; }
        public virtual 物料资料 物料资料 { get; set; }
        public virtual 用户 用户 { get; set; }
    }
}
